export const shopCategories = [
    { value: "baby_kids", label: "Baby & Kids Store" },
    { value: "art_craft", label: "Art & Craft Supplies" },
    { value: "music", label: "Music Instruments & Stores" },
    { value: "technology", label: "Software & Technology Services" },
    { value: "garden", label: "Garden & Outdoor Equipment" },
    { value: "bakery", label: "Bakery & Confectionery" },
    { value: "optical", label: "Optical & Eyewear" },
    { value: "mobile", label: "Mobile Phones & Accessories" },
    { value: "real_estate", label: "Real Estate & Property Services" },
    { value: "fitness", label: "Fitness & Wellness Centers" },
    { value: "entertainment", label: "Entertainment & Gaming" },
    { value: "fashion", label: "Clothing & Fashion" },
    { value: "footwear", label: "Footwear & Accessories" },
    { value: "jewelry", label: "Jewelry & Watches" },
    { value: "electronics", label: "Electronics & Appliances" },
    { value: "furniture", label: "Furniture & Home Decor" },
    { value: "grocery", label: "Grocery & General Store" },
    { value: "books", label: "Books & Stationery" },
    { value: "beauty", label: "Beauty & Personal Care" },
    { value: "pharmacy", label: "Pharmacy & Health Store" },
    { value: "automotive", label: "Automotive & Spare Parts" },
    { value: "pet_supplies", label: "Pet Supplies & Services" },
    { value: "hardware", label: "Hardware & Tools" },
    { value: "toys", label: "Toys, Games & Collectibles" },
    { value: "food_beverages", label: "Food & Beverages" },
    { value: "travel", label: "Travel & Tourism Services" },
    { value: "hospitality", label: "Hotels & Restaurants" },
    { value: "education", label: "Education & Training Services" },
    { value: "finance", label: "Financial & Banking Services" },
    { value: "events", label: "Events & Party Services" },
    { value: "other", label: "Other" },
  ];
  