import { Toaster } from 'react-hot-toast';
// @ts-ignore
import './global.css';
import Providers from './Providers';
import {Poppins} from 'next/font/google'
import SidebarWrapper from './shared/components/sidebar';



const poppins = Poppins({
  subsets:["latin"],
  weight:["100","300","400","500","700","900"],
  variable:"--font-poppins"
})


export const metadata = {
  title: 'Eshop Seller',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={`min-h-screen bg-slate-900 font-sans antialiased ${poppins.variable}`} >
        <Providers>
          <Toaster />
     {children}
        
        </Providers>
        </body>
    </html>
  )
}
